name: "Deploy App"

on:
  push:
    branches:
      - main
      - docker-on-ec2

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          #Set Java Version
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Build with maven
        run: mvn -B package --file backend/pom.xml

      - uses: actions/upload-artifact@v2
        with:
          name: app.jar
          path: backend/target/app.jar

  push-to-docker-hub:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: app.jar
          path: backend/target

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          #Set dockerhub username
          username: bartfastiel
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          #Set dockerhub username/projectName
          tags: bartfastiel/deploy-to-aws-with-github-action:latest
          context: .

  deploy:
    runs-on: ubuntu-latest
    needs: push-to-docker-hub
    steps:
      - name: Restart docker container
        uses: appleboy/ssh-action@master
        with:
          host: capstone-project.de
          #Set App Name ("alpha" - "tango")
          username: alpha
          password: ${{ secrets.SSH_PASSWORD }}
          #Set App Name ("alpha" - "tango")
          #Set dockerhub project
          #Set IP ("10.0.1.1" - "10.0.1.20")
          script: |
            docker stop alpha
            docker rm alpha
            docker run --pull=always --name alpha --network capstones --ip 10.0.1.1 --detach bartfastiel/deploy-to-aws-with-github-actions:latest
            sleep 15s
            docker logs alpha
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          #Set App Name ("alpha" - "tango")
          url: http://alpha.capstone-project.de
          max-attempts: 3
          retry-delay: 5s
          retry-all: true
